import * as Yup from "yup";
export const artistValidationSchema = Yup.object({
  name: Yup.string().required("Name field is required"),
  email: Yup.string().email().required("Email field is required"),
  sharePersonal: Yup.string().required("Choose an option"),
  instagram: Yup.string(),
  twitter: Yup.string(),
  discord: Yup.string(),
  otherPlatform: Yup.string(),
  otherUsername: Yup.string(),
  everWorked: Yup.string().required("Choose an option"),
  wasRole: Yup.string(),
  everWorkedWith: Yup.string().required("Choose an option"),
  areYouWilling: Yup.string().required("Choose an option"),
  mostInterested: Yup.string().required("Choose an option"),
  introduce: Yup.string(),
});
export const authorValidationSchema = Yup.object({
  name: Yup.string().required("Name field is required"),
  email: Yup.string().email().required("Email field is required"),
  sharePersonal: Yup.string().required("Choose an option"),
  instagram: Yup.string(),
  twitter: Yup.string(),
  discord: Yup.string(),
  otherPlatform: Yup.string(),
  otherUsername: Yup.string(),
  everWorked: Yup.string().required("Choose an option"),
  prevWork: Yup.string(),
  whichMore: Yup.array(),
  whyDoYou: Yup.string(),
  haveIdea: Yup.string(),
  areYouInterested: Yup.string().required("Choose an option"),
  willTakePlace: Yup.string().required("Choose an option"),
  whatNFTis: Yup.string().required("Choose an option"),
  introduce: Yup.string(),
});
