export const artistFormInputs = [
  {
    control: "input",
    id: "name",
    name: "name",
    type: "text",
    label: "Your name",
    placeholder: "Type in Your Name",
    required: true,
  },
  {
    control: "input",
    id: "email",
    name: "email",
    type: "email",
    label: "Your Email",
    placeholder: "Type in Your email",
    required: true,
  },
  {
    control: "radio",
    id: "sharePersonal",
    name: "sharePersonal",
    label: "Are you comfortable sharing your identity with our community?",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "input",
    id: "instagram",
    name: "instagram",
    type: "text",
    label: "instagram handle",
    placeholder: "",
    withIcon: true,
    required: false,
  },
  {
    control: "input",
    id: "discord",
    name: "discord",
    type: "text",
    label: "discord handle",
    placeholder: "",
    withIcon: true,
    required: false,
  },
  {
    control: "input",
    id: "twitter",
    name: "twitter",
    type: "text",
    label: "twitter handle",
    placeholder: "",
    withIcon: true,
    required: false,
  },
  {
    control: "multi-input",
    name: "other",
    label:
      "ANY OTHER PLATFORM YOU HAVE A PORTFOLIO ON? WRITE IT IN THIS FORMAT BELOW (BEHANCE: @USERNAME)",
    inputs: [
      {
        id: "otherPlatform",
        name: "otherPlatform",
        type: "text",
        placeholder: "",
        withIcon: true,
        required: false,
      },
      {
        id: "otherUsername",
        name: "otherUsername",
        type: "text",
        placeholder: "",
        required: false,
      },
    ],
  },

  {
    control: "radio",
    id: "everWorked",
    name: "everWorked",
    label: "HAVE YOU EVER WORKED ON A COMIC BOOK BEFORE?",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "input",
    id: "wasRole",
    name: "wasRole",
    label: "What was your role?",
    type: "text",
    required: true,
  },

  {
    control: "radio",
    id: "everWorkedWith",
    name: "everWorkedWith",
    label:
      "HAVE YOU EVER WORKED COLLABORATIVELY WITH OTHER ARTISTS ON A PROJECT?",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "radio",
    id: "areYouWilling",
    name: "areYouWilling",
    label:
      "ARE YOU WILLING TO WORK COLLABORATIVELY WITH OTHER ARTISTS ON A COMIC BOOK?",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "radio",
    id: "mostInterested",
    name: "mostInterested",
    label: "WHICH OF OUR OFFERINGS ARE YOU MOST INTERESTED IN?",
    row: false,
    type: "radio",
    options: [
      {
        key: "Translating script into layout and base sketches",
        value: "translating",
      },
      { key: "Creating final line art and outlines", value: "creating" },
      { key: "Coloring and detailing", value: "coloring" },
    ],
    required: true,
  },
  {
    control: "textarea",
    id: "introduce",
    name: "introduce",
    type: "text",
    label:
      "IF THERE IS ANYTHING ELSE YOU THINK MAY STRENGTHEN YOUR APPLICATION PLEASE RESPOND BELOW",
    rows: 8,
    placeholder: "Describe yourself",
    required: false,
  },
];
