export const authorFormInputs = [
  {
    control: "input",
    id: "name",
    name: "name",
    type: "text",
    label: "Your name",
    placeholder: "Type in Your Name",
    required: true,
  },
  {
    control: "input",
    id: "email",
    name: "email",
    type: "email",
    label: "Your Email",
    placeholder: "Type in Your email",
    required: true,
  },
  {
    control: "radio",
    id: "sharePersonal",
    name: "sharePersonal",
    label: "Are you comfortable sharing your identity with our community?",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "input",
    id: "instagram",
    name: "instagram",
    type: "text",
    label: "instagram handle",
    placeholder: "",
    withIcon: true,
    required: false,
  },
  {
    control: "input",
    id: "discord",
    name: "discord",
    type: "text",
    label: "discord handle",
    placeholder: "",
    withIcon: true,
    required: false,
  },
  {
    control: "input",
    id: "twitter",
    name: "twitter",
    type: "text",
    label: "twitter handle",
    placeholder: "",
    withIcon: true,
    required: false,
  },
  {
    control: "multi-input",
    label:
      "ANY OTHER PLATFORM YOU HAVE A PORTFOLIO ON? WRITE IT IN THIS FORMAT BELOW (BEHANCE: @USERNAME)",
    inputs: [
      {
        id: "otherPlatform",
        name: "otherPlatform",
        type: "text",
        placeholder: "",
        withIcon: true,
        required: false,
      },
      {
        id: "otherUsername",
        name: "otherUsername",
        type: "text",
        placeholder: "",
        required: false,
      },
    ],
  },
  {
    control: "radio",
    id: "everWorked",
    name: "everWorked",
    label: "HAVE YOU EVER WORKED ON A COMIC BOOK BEFORE?",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "input",
    id: "prevWork",
    name: "prevWork",
    label: "Share link on your previous work",
    type: "text",
    placeholder: "Link on your last work",
    required: false,
  },
  {
    control: "radio",
    id: "whichMore",
    name: "whichMore",
    label: "WHICH OF OUR OFFERINGS ARE YOU MOST INTERESTED IN?*",
    row: false,
    type: "checkbox",
    options: [
      { key: "Branding", value: "branding" },
      { key: "Publishing", value: "publishing" },
      { key: "community", value: "community" },
      { key: "artist network", value: "artist network" },
      { key: "funding", value: "funding" },
      { key: "characters", value: "characters" },
    ],
    required: true,
  },
  {
    control: "textarea",
    id: "whyDoYou",
    name: "whyDoYou",
    type: "text",
    label: "Why do you want to work with us?",
    rows: 4,
    placeholder: " Tell us more about yourself",
    required: false,
  },
  {
    control: "textarea",
    id: "haveIdea",
    name: "haveIdea",
    type: "text",
    label:
      "DO YOU HAVE AN IDEA FOR A COMIC BOOK? IF YES, PLEA SE DESCRIBE THE IDEA",
    rows: 4,
    placeholder: "Describe your idea",
    required: false,
  },
  {
    control: "radio",
    id: "areYouInterested",
    name: "areYouInterested",
    label:
      "ARE YOU INTERESTED IN USING OUR OTAKUS OR ANY OTHER CHARACTER WE OWN IN YOUR STORY?",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "radio",
    id: "willTakePlace",
    name: "willTakePlace",
    label: "WILL YOUR STORY TAKE PLACE WITHIN THE OTAKUVERSE?",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "radio",
    id: "whatNFTis",
    name: "whatNFTis",
    label: "DO YOU KNOW WHAT AN NFT IS?*",
    row: true,
    type: "radio",
    options: [
      { key: "Yes", value: "yes" },
      { key: "No", value: "no" },
    ],
    required: true,
  },
  {
    control: "textarea",
    id: "introduce",
    name: "introduce",
    type: "text",
    label:
      "IF THERE IS ANYTHING ELSE YOU THINK MAY STRENGTHEN YOUR APPLICATION PLEASE RESPOND BELOW",
    rows: 8,
    placeholder: "Describe yourself",
    required: false,
  },
];
