export const clothes = {
  captain_jacket: {
    rarity: 142,
    label: "Captain Jacket",
    1: "/assets/builder/traits/clothes/1/captain_jacket.png",
    2: "/assets/builder/traits/clothes/2/captain_jacket.png",
    3: "/assets/builder/traits/clothes/3/captain_jacket.png",
  },
  cowboy_jacket: {
    rarity: 151,
    label: "Cowboy Jacket",
    1: "/assets/builder/traits/clothes/1/cowboy_jacket.png",
    2: "/assets/builder/traits/clothes/2/cowboy_jacket.png",
    3: "/assets/builder/traits/clothes/3/cowboy_jacket.png",
  },
  freedom_jacket: {
    rarity: 100,
    label: "Freedom Jacket",
    1: "/assets/builder/traits/clothes/1/freedom_jacket.png",
    2: "/assets/builder/traits/clothes/2/freedom_jacket.png",
    3: "/assets/builder/traits/clothes/3/freedom_jacket.png",
  },
  inferno_jacket: {
    rarity: 69,
    label: "Inferno Jacket",
    1: "/assets/builder/traits/clothes/1/inferno_jacket.png",
    2: "/assets/builder/traits/clothes/2/inferno_jacket.png",
    3: "/assets/builder/traits/clothes/3/inferno_jacket.png",
  },
  hunter_shirt_and_chain: {
    rarity: 186,
    label: "Hunter Shirt & Chain",
    1: "/assets/builder/traits/clothes/1/hunter_shirt_and_chain.png",
    2: "/assets/builder/traits/clothes/2/hunter_shirt_and_chain.png",
    3: "/assets/builder/traits/clothes/3/hunter_shirt_and_chain.png",
  },
  fusion_tank_top: {
    rarity: 53,
    label: "Fusion Tank Top",
    1: "/assets/builder/traits/clothes/1/fusion_tank_top.png",
    2: "/assets/builder/traits/clothes/2/fusion_tank_top.png",
    3: "/assets/builder/traits/clothes/3/fusion_tank_top.png",
  },
  ghoul_shirt: {
    rarity: 105,
    label: "Ghoul Shirt",
    1: "/assets/builder/traits/clothes/1/ghoul_shirt.png",
    2: "/assets/builder/traits/clothes/2/ghoul_shirt.png",
    3: "/assets/builder/traits/clothes/3/ghoul_shirt.png",
  },
  black_shirt_and_red_tie: {
    rarity: 150,
    label: "Black Shirt & Red Tie",
    1: "/assets/builder/traits/clothes/1/black_shirt_and_red_tie.png",
    2: "/assets/builder/traits/clothes/2/black_shirt_and_red_tie.png",
    3: "/assets/builder/traits/clothes/3/black_shirt_and_red_tie.png",
  },
  beast_chakra_sleeveless_hoodie: {
    rarity: 48,
    label: "Beast Chakra Hoodie",
    1: "/assets/builder/traits/clothes/1/beast_chakra_sleeveless_hoodie.png",
    2: "/assets/builder/traits/clothes/2/beast_chakra_sleeveless_hoodie.png",
    3: "/assets/builder/traits/clothes/3/beast_chakra_sleeveless_hoodie.png",
  },
  bulls_jersey: {
    rarity: 50,
    label: "Bulls Jersey",
    1: "/assets/builder/traits/clothes/1/bulls_jersey.png",
    2: "/assets/builder/traits/clothes/2/bulls_jersey.png",
    3: "/assets/builder/traits/clothes/3/bulls_jersey.png",
  },
  crow_jersey: {
    rarity: 202,
    label: "Crow Jersey",
    1: "/assets/builder/traits/clothes/1/crow_jersey.png",
    2: "/assets/builder/traits/clothes/2/crow_jersey.png",
    3: "/assets/builder/traits/clothes/3/crow_jersey.png",
  },
  dawn_jersey: {
    rarity: 53,
    label: "Dawn Jersey",
    1: "/assets/builder/traits/clothes/1/dawn_jersey.png",
    2: "/assets/builder/traits/clothes/2/dawn_jersey.png",
    3: "/assets/builder/traits/clothes/3/dawn_jersey.png",
  },
  demon_yellow_hawaiian: {
    rarity: 117,
    label: "Demon Yellow Hawaiian",
    1: "/assets/builder/traits/clothes/1/demon_yellow_hawaiian.png",
    2: "/assets/builder/traits/clothes/2/demon_yellow_hawaiian.png",
    3: "/assets/builder/traits/clothes/3/demon_yellow_hawaiian.png",
  },
  green_and_black_hawaiian: {
    rarity: 80,
    label: "Green & Black Hawaiian",
    1: "/assets/builder/traits/clothes/1/green_and_black_hawaiian.png",
    2: "/assets/builder/traits/clothes/2/green_and_black_hawaiian.png",
    3: "/assets/builder/traits/clothes/3/green_and_black_hawaiian.png",
  },
  flower_hawaiian_and_x_scar: {
    rarity: 202,
    label: "Flower Hawaiian & X Scar",
    1: "/assets/builder/traits/clothes/1/flower_hawaiian_and_x_scar.png",
    2: "/assets/builder/traits/clothes/2/flower_hawaiian_and_x_scar.png",
    3: "/assets/builder/traits/clothes/3/flower_hawaiian_and_x_scar.png",
  },
  banana_hawaiian_and_drill_necklace: {
    rarity: 79,
    label: "Banana Hawaiian",
    1: "/assets/builder/traits/clothes/1/banana_hawaiian_and_drill_necklace.png",
    2: "/assets/builder/traits/clothes/2/banana_hawaiian_and_drill_necklace.png",
    3: "/assets/builder/traits/clothes/3/banana_hawaiian_and_drill_necklace.png",
  },
  demon_yellow_shirt: {
    rarity: 119,
    label: "Demon Yellow Shirt",
    1: "/assets/builder/traits/clothes/1/demon_yellow_shirt.png",
    2: "/assets/builder/traits/clothes/2/demon_yellow_shirt.png",
    3: "/assets/builder/traits/clothes/3/demon_yellow_shirt.png",
  },
  egyptian_jacket_and_puzzle: {
    rarity: 98,
    label: "Egyptian Jacket & Puzzle",
    1: "/assets/builder/traits/clothes/1/egyptian_jacket_and_puzzle.png",
    2: "/assets/builder/traits/clothes/2/egyptian_jacket_and_puzzle.png",
    3: "/assets/builder/traits/clothes/3/egyptian_jacket_and_puzzle.png",
  },
  air_tribe_hoodie: {
    rarity: 96,
    label: "Air Tribe Hoodie",
    1: "/assets/builder/traits/clothes/1/air_tribe_hoodie.png",
    2: "/assets/builder/traits/clothes/2/air_tribe_hoodie.png",
    3: "/assets/builder/traits/clothes/3/air_tribe_hoodie.png",
  },
  earth_tribe_hoodie: {
    rarity: 131,
    label: "Earth Tribe Hoodie",
    1: "/assets/builder/traits/clothes/1/earth_tribe_hoodie.png",
    2: "/assets/builder/traits/clothes/2/earth_tribe_hoodie.png",
    3: "/assets/builder/traits/clothes/3/earth_tribe_hoodie.png",
  },
  fire_tribe_hoodie: {
    rarity: 135,
    label: "Fire Tribe Hoodie",
    1: "/assets/builder/traits/clothes/1/fire_tribe_hoodie.png",
    2: "/assets/builder/traits/clothes/2/fire_tribe_hoodie.png",
    3: "/assets/builder/traits/clothes/3/fire_tribe_hoodie.png",
  },
  fire_fighter_hoodie: {
    rarity: 138,
    label: "Fire Fighter Hoodie",
    1: "/assets/builder/traits/clothes/1/fire_fighter_hoodie.png",
    2: "/assets/builder/traits/clothes/2/fire_fighter_hoodie.png",
    3: "/assets/builder/traits/clothes/3/fire_fighter_hoodie.png",
  },
  laws_hoodie: {
    rarity: 82,
    label: "Laws Hoodie",
    1: "/assets/builder/traits/clothes/1/laws_hoodie.png",
    2: "/assets/builder/traits/clothes/2/laws_hoodie.png",
    3: "/assets/builder/traits/clothes/3/laws_hoodie.png",
  },
  laws_sleeveless_hoodie: {
    rarity: 57,
    label: "Laws Sleveless Hoodie",
    1: "/assets/builder/traits/clothes/1/laws_sleeveless_hoodie.png",
    2: "/assets/builder/traits/clothes/2/laws_sleeveless_hoodie.png",
    3: "/assets/builder/traits/clothes/3/laws_sleeveless_hoodie.png",
  },
  pink_sleeveless_hoodie: {
    rarity: 73,
    label: "Pink Sleveless Hoodie",
    1: "/assets/builder/traits/clothes/1/pink_sleeveless_hoodie.png",
    2: "/assets/builder/traits/clothes/2/pink_sleeveless_hoodie.png",
    3: "/assets/builder/traits/clothes/3/pink_sleeveless_hoodie.png",
  },
  nine_tails_shirt: {
    rarity: 189,
    label: "Nine Tails Shirt",
    1: "/assets/builder/traits/clothes/1/nine_tails_shirt.png",
    2: "/assets/builder/traits/clothes/2/nine_tails_shirt.png",
    3: "/assets/builder/traits/clothes/3/nine_tails_shirt.png",
  },
  origins_shirt: {
    rarity: 211,
    label: "Origins Shirt",
    1: "/assets/builder/traits/clothes/1/origins_shirt.png",
    2: "/assets/builder/traits/clothes/2/origins_shirt.png",
    3: "/assets/builder/traits/clothes/3/origins_shirt.png",
  },
  rogue_shirt: {
    rarity: 32,
    label: "Rogue Shinobi Shirt",
    1: "/assets/builder/traits/clothes/1/rogue_shinobi_shirt.png",
    2: "/assets/builder/traits/clothes/2/rogue_shinobi_shirt.png",
    3: "/assets/builder/traits/clothes/3/rogue_shinobi_shirt.png",
  },
  pain_tank_top: {
    rarity: 194,
    label: "Pain Tank Top",
    1: "/assets/builder/traits/clothes/1/pain_tank_top.png",
    2: "/assets/builder/traits/clothes/2/pain_tank_top.png",
    3: "/assets/builder/traits/clothes/3/pain_tank_top.png",
  },
  prince_tank_top: {
    rarity: 38,
    label: "Prince Tank Top",
    1: "/assets/builder/traits/clothes/1/prince_tank_top.png",
    2: "/assets/builder/traits/clothes/2/prince_tank_top.png",
    3: "/assets/builder/traits/clothes/3/prince_tank_top.png",
  },
  reaper_tank_top: {
    rarity: 100,
    label: "Reaper Tank Top",
    1: "/assets/builder/traits/clothes/1/reaper_tank_top.png",
    2: "/assets/builder/traits/clothes/2/reaper_tank_top.png",
    3: "/assets/builder/traits/clothes/3/reaper_tank_top.png",
  },
  panda_shirt: {
    rarity: 210,
    label: "Panda Shirt",
    1: "/assets/builder/traits/clothes/1/panda_shirt.png",
    2: "/assets/builder/traits/clothes/2/panda_shirt.png",
    3: "/assets/builder/traits/clothes/3/panda_shirt.png",
  },
  ramen_shirt: {
    rarity: 135,
    label: "Ramen Shirt",
    1: "/assets/builder/traits/clothes/1/ramen_shirt.png",
    2: "/assets/builder/traits/clothes/2/ramen_shirt.png",
    3: "/assets/builder/traits/clothes/3/ramen_shirt.png",
  },
  shinobi_hoodie: {
    rarity: 62,
    label: "Shinobi Hoodie",
    1: "/assets/builder/traits/clothes/1/shinobi_hoodie.png",
    2: "/assets/builder/traits/clothes/2/shinobi_hoodie.png",
    3: "/assets/builder/traits/clothes/3/shinobi_hoodie.png",
  },
  short_sleeve_hoodie_and_flute: {
    rarity: 168,
    label: "ShortSleeve Hoodie & Flute",
    1: "/assets/builder/traits/clothes/1/short_sleeve_hoodie_and_flute.png",
    2: "/assets/builder/traits/clothes/2/short_sleeve_hoodie_and_flute.png",
    3: "/assets/builder/traits/clothes/3/short_sleeve_hoodie_and_flute.png",
  },
  slime_shirt: {
    rarity: 104,
    label: "Slime Shirt",
    1: "/assets/builder/traits/clothes/1/slime_shirt.png",
    2: "/assets/builder/traits/clothes/2/slime_shirt.png",
    3: "/assets/builder/traits/clothes/3/slime_shirt.png",
  },
  sol_hoodie_and_chain: {
    rarity: 170,
    label: "Sol Hoodie & Chain",
    1: "/assets/builder/traits/clothes/1/sol_hoodie_and_chain.png",
    2: "/assets/builder/traits/clothes/2/sol_hoodie_and_chain.png",
    3: "/assets/builder/traits/clothes/3/sol_hoodie_and_chain.png",
  },
  ua_hoodie: {
    rarity: 138,
    label: "UA Hoodie",
    1: "/assets/builder/traits/clothes/1/ua_hoodie.png",
    2: "/assets/builder/traits/clothes/2/ua_hoodie.png",
    3: "/assets/builder/traits/clothes/3/ua_hoodie.png",
  },
  water_tribe_hoodie: {
    rarity: 108,
    label: "Water Tribe Hoodie",
    1: "/assets/builder/traits/clothes/1/water_tribe_hoodie.png",
    2: "/assets/builder/traits/clothes/2/water_tribe_hoodie.png",
    3: "/assets/builder/traits/clothes/3/water_tribe_hoodie.png",
  },
  z_jersey: {
    rarity: 45,
    label: "Z Jersey",
    1: "/assets/builder/traits/clothes/1/z_jersey.png",
    2: "/assets/builder/traits/clothes/2/z_jersey.png",
    3: "/assets/builder/traits/clothes/3/z_jersey.png",
  },
};
