export const hairs = {
  none: {
    rarity: 87,
    label: "None",
    white: "/assets/builder/traits/head/white/none.png",
    black: "/assets/builder/traits/head/black/none.png",
  },
  "100_cap": {
    rarity: 106,
    label: "100 Cap",
    white: "/assets/builder/traits/head/white/100_cap.png",
    black: "/assets/builder/traits/head/black/100_cap.png",
  },
  antenna_and_assassin_hairstyle: {
    rarity: 66,
    label: "Antenna & Assassin Hairstyle",
    white:
      "/assets/builder/traits/head/white/antenna_and_assassin_hairstyle.png",
    black:
      "/assets/builder/traits/head/black/antenna_and_assassin_hairstyle.png",
  },
  antenna_and_dark_blue_hairstyle: {
    rarity: 107,
    label: "Antenna & Dark Blue Hairstyle",
    white:
      "/assets/builder/traits/head/white/antenna_and_dark_blue_hairstyle.png",
    black:
      "/assets/builder/traits/head/black/antenna_and_dark_blue_hairstyle.png",
  },
  assassin_hairstyle: {
    rarity: 151,
    label: "Assassin Hairstyle",
    white: "/assets/builder/traits/head/white/assassin_hairstyle.png",
    black: "/assets/builder/traits/head/black/assassin_hairstyle.png",
  },
  black_hairstyle: {
    rarity: 152,
    label: "Black Hairstyle",
    white: "/assets/builder/traits/head/white/black_hairstyle.png",
    black: "/assets/builder/traits/head/black/black_hairstyle.png",
  },
  brotherhood_beanie: {
    rarity: 57,
    label: "Brotherhood Beanie",
    white: "/assets/builder/traits/head/white/brotherhood_beanie.png",
    black: "/assets/builder/traits/head/black/brotherhood_beanie.png",
  },
  buzz_cut_hairstyle: {
    rarity: 132,
    label: "Buzz Cut Hairstyle",
    white: "/assets/builder/traits/head/white/buzz_cut_hairstyle.png",
    black: "/assets/builder/traits/head/black/buzz_cut_hairstyle.png",
  },
  cloudy_bucket_hat: {
    rarity: 2,
    label: "Cloudy Bucket Hat",
    white: "/assets/builder/traits/head/white/cloudy_bucket_hat.png",
    black: "/assets/builder/traits/head/black/cloudy_bucket_hat.png",
  },
  crows_cap: {
    rarity: 142,
    label: "Crows Cap",
    white: "/assets/builder/traits/head/white/crows_cap.png",
    black: "/assets/builder/traits/head/black/crows_cap.png",
  },
  delinquents_hat: {
    rarity: 25,
    label: "Delinquents Hat",
    white: "/assets/builder/traits/head/white/delinquents_hat.png",
    black: "/assets/builder/traits/head/black/delinquents_hat.png",
  },
  demon_hairstyle: {
    rarity: 2,
    label: "Demon Hairstyle",
    white: "/assets/builder/traits/head/white/demon_hairstyle.png",
    black: "/assets/builder/traits/head/black/demon_hairstyle.png",
  },
  devils_hairstyle: {
    rarity: 91,
    label: "Devils Hairstyle",
    white: "/assets/builder/traits/head/white/devils_hairstyle.png",
    black: "/assets/builder/traits/head/black/devils_hairstyle.png",
  },
  dimples_beanie: {
    rarity: 78,
    label: "Dimples Beanie",
    white: "/assets/builder/traits/head/white/dimples_beanie.png",
    black: "/assets/builder/traits/head/black/dimples_beanie.png",
  },
  doctors_hat: {
    rarity: 82,
    label: "Doctors Hat",
    white: "/assets/builder/traits/head/white/doctors_hat.png",
    black: "/assets/builder/traits/head/black/doctors_hat.png",
  },
  freedom_beanie: {
    rarity: 124,
    label: "Freedom Beanie",
    white: "/assets/builder/traits/head/white/freedom_beanie.png",
    black: "/assets/builder/traits/head/black/freedom_beanie.png",
  },
  frosted_man_bun_hairstyle: {
    rarity: 133,
    label: "Frosted Man Bun Hairstyle",
    white: "/assets/builder/traits/head/white/frosted_man_bun_hairstyle.png",
    black: "/assets/builder/traits/head/black/frosted_man_bun_hairstyle.png",
  },
  frosted_tips_hairstyle: {
    rarity: 114,
    label: "Frosted Tips Hairstyle",
    white: "/assets/builder/traits/head/white/frosted_tips_hairstyle.png",
    black: "/assets/builder/traits/head/black/frosted_tips_hairstyle.png",
  },
  goggles: {
    rarity: 131,
    label: "Goggles",
    white: "/assets/builder/traits/head/white/goggles.png",
    black: "/assets/builder/traits/head/black/goggles.png",
  },
  green_hairstyle: {
    rarity: 152,
    label: "Green Hairstyle",
    white: "/assets/builder/traits/head/white/green_hairstyle.png",
    black: "/assets/builder/traits/head/black/green_hairstyle.png",
  },
  grey_hairstyle: {
    rarity: 159,
    label: "Grey Hairstyle",
    white: "/assets/builder/traits/head/white/grey_hairstyle.png",
    black: "/assets/builder/traits/head/black/grey_hairstyle.png",
  },
  halo: {
    rarity: 97,
    label: "Halo",
    white: "/assets/builder/traits/head/white/halo.png",
    black: "/assets/builder/traits/head/black/halo.png",
  },
  icy_hot_hairstyle: {
    rarity: 99,
    label: "Icy Hot Hairstyle",
    white: "/assets/builder/traits/head/white/icy_hot_hairstyle.png",
    black: "/assets/builder/traits/head/black/icy_hot_hairstyle.png",
  },
  kings_crown: {
    rarity: 112,
    label: "Kings Crown",
    white: "/assets/builder/traits/head/white/kings_crown.png",
    black: "/assets/builder/traits/head/black/kings_crown.png",
  },
  l_cap: {
    rarity: 121,
    label: "L cap",
    white: "/assets/builder/traits/head/white/l_cap.png",
    black: "/assets/builder/traits/head/black/l_cap.png",
  },
  light_green_hairstyle: {
    rarity: 128,
    label: "Light Green Hairstyle",
    white: "/assets/builder/traits/head/white/light_green_hairstyle.png",
    black: "/assets/builder/traits/head/black/light_green_hairstyle.png",
  },
  light_hairstyle: {
    rarity: 123,
    label: "Light Hairstyle",
    white: "/assets/builder/traits/head/white/light_hairstyle.png",
    black: "/assets/builder/traits/head/black/light_hairstyle.png",
  },
  lion_beanie: {
    rarity: 122,
    label: "Lion Beanie",
    white: "/assets/builder/traits/head/white/lion_beanie.png",
    black: "/assets/builder/traits/head/black/lion_beanie.png",
  },
  long_grey_hairstyle: {
    rarity: 148,
    label: "Long Grey Hairstyle",
    white: "/assets/builder/traits/head/white/long_grey_hairstyle.png",
    black: "/assets/builder/traits/head/black/long_grey_hairstyle.png",
  },
  loop_hairstyle: {
    rarity: 22,
    label: "Loop Hairstyle",
    white: "/assets/builder/traits/head/white/loop_hairstyle.png",
    black: "/assets/builder/traits/head/black/loop_hairstyle.png",
  },
  man_bun_hairstyle: {
    rarity: 125,
    label: "Man Bun Hairstyle",
    white: "/assets/builder/traits/head/white/man_bun_hairstyle.png",
    black: "/assets/builder/traits/head/black/man_bun_hairstyle.png",
  },
  mohawk: {
    rarity: 141,
    label: "Mohawk",
    white: "/assets/builder/traits/head/white/mohawk.png",
    black: "/assets/builder/traits/head/black/mohawk.png",
  },
  one_million_bucket_hat: {
    rarity: 109,
    label: "One Million Bucket Hat",
    white: "/assets/builder/traits/head/white/one_million_bucket_hat.png",
    black: "/assets/builder/traits/head/black/one_million_bucket_hat.png",
  },
  origins_beanie: {
    rarity: 150,
    label: "Origins Beanie",
    white: "/assets/builder/traits/head/white/origins_beanie.png",
    black: "/assets/builder/traits/head/black/origins_beanie.png",
  },
  pirate_king_bucket_hat: {
    rarity: 33,
    label: "Pirate King Bucket Hat",
    white: "/assets/builder/traits/head/white/pirate_king_bucket_hat.png",
    black: "/assets/builder/traits/head/black/pirate_king_bucket_hat.png",
  },
  red_hairstyle: {
    rarity: 122,
    label: "Red Hairstyle",
    white: "/assets/builder/traits/head/white/red_hairstyle.png",
    black: "/assets/builder/traits/head/black/red_hairstyle.png",
  },
  shield_bucket_hat: {
    rarity: 157,
    label: "Shield Bucket Hat",
    white: "/assets/builder/traits/head/white/shield_bucket_hat.png",
    black: "/assets/builder/traits/head/black/shield_bucket_hat.png",
  },
  short_mohawk_hairstyle: {
    rarity: 163,
    label: "Short Mohawk Hairstyle",
    white: "/assets/builder/traits/head/white/short_mohawk_hairstyle.png",
    black: "/assets/builder/traits/head/black/short_mohawk_hairstyle.png",
  },
  soccer_cap: {
    rarity: 136,
    label: "Soccer Cap",
    white: "/assets/builder/traits/head/white/soccer_cap.png",
    black: "/assets/builder/traits/head/black/soccer_cap.png",
  },
  soccer_hairstyle: {
    rarity: 165,
    label: "Soccer Hairstyle",
    white: "/assets/builder/traits/head/white/soccer_hairstyle.png",
    black: "/assets/builder/traits/head/black/soccer_hairstyle.png",
  },
  spike_hairstyle: {
    rarity: 122,
    label: "Spike Hairstyle",
    white: "/assets/builder/traits/head/white/spike_hairstyle.png",
    black: "/assets/builder/traits/head/black/spike_hairstyle.png",
  },
  spiky_red_hairstyle: {
    rarity: 164,
    label: "Spiky Red Hairstyle",
    white: "/assets/builder/traits/head/white/spiky_red_hairstyle.png",
    black: "/assets/builder/traits/head/black/spiky_red_hairstyle.png",
  },
  spirit_crown: {
    rarity: 14,
    label: "Spirit Crown",
    white: "/assets/builder/traits/head/white/spirit_crown.png",
    black: "/assets/builder/traits/head/black/spirit_crown.png",
  },
  super_blue_hairstyle: {
    rarity: 21,
    label: "Super Blue Hairstyle",
    white: "/assets/builder/traits/head/white/super_blue_hairstyle.png",
    black: "/assets/builder/traits/head/black/super_blue_hairstyle.png",
  },
  super_hairstyle: {
    rarity: 53,
    label: "Super Hairstyle",
    white: "/assets/builder/traits/head/white/super_hairstyle.png",
    black: "/assets/builder/traits/head/black/super_hairstyle.png",
  },
  teachers_bucket_hat: {
    rarity: 62,
    label: "Teachers Bucket Hat",
    white: "/assets/builder/traits/head/white/teachers_bucket_hat.png",
    black: "/assets/builder/traits/head/black/teachers_bucket_hat.png",
  },
  the_pirate_king_cap: {
    rarity: 42,
    label: "The Pirate King Cap",
    white: "/assets/builder/traits/head/white/the_pirate_king_cap.png",
    black: "/assets/builder/traits/head/black/the_pirate_king_cap.png",
  },
  titan_cap: {
    rarity: 83,
    label: "Titan Cap",
    white: "/assets/builder/traits/head/white/titan_cap.png",
    black: "/assets/builder/traits/head/black/titan_cap.png",
  },
  ua_beanie: {
    rarity: 67,
    label: "UA Beanie",
    white: "/assets/builder/traits/head/white/ua_beanie.png",
    black: "/assets/builder/traits/head/black/ua_beanie.png",
  },
};
