export const weapons = {
  demon_katana: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/demon_katana.png",
    tan: "/assets/builder/traits/weapon/tan/1/demon_katana.png",
    black: "/assets/builder/traits/weapon/black/1/demon_katana.png",
    label: "Demon Katana",
    rarity: 179,
  },
  emperor_sword: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/emperor_sword.png",
    tan: "/assets/builder/traits/weapon/tan/1/emperor_sword.png",
    black: "/assets/builder/traits/weapon/black/1/emperor_sword.png",
    label: "Emperor Sword",
    rarity: 117,
  },
  dragon_sword: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/dragon_sword.png",
    tan: "/assets/builder/traits/weapon/tan/1/dragon_sword.png",
    black: "/assets/builder/traits/weapon/black/1/dragon_sword.png",
    label: "Dragon Sword",
    rarity: 231,
  },
  excalibur: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/excalibur.png",
    tan: "/assets/builder/traits/weapon/tan/1/excalibur.png",
    black: "/assets/builder/traits/weapon/black/1/excalibur.png",
    label: "Excalibur",
    rarity: 52,
  },
  kunai: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/kunai.png",
    tan: "/assets/builder/traits/weapon/tan/1/kunai.png",
    black: "/assets/builder/traits/weapon/black/1/kunai.png",
    label: "kunai",
    rarity: 189,
  },
  legendary_kunai: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/legendary_kunai.png",
    tan: "/assets/builder/traits/weapon/tan/1/legendary_kunai.png",
    black: "/assets/builder/traits/weapon/black/1/legendary_kunai.png",
    label: "Legendary Kunai",
    rarity: 90,
  },
  long_blade_katana: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/long_blade_katana.png",
    tan: "/assets/builder/traits/weapon/tan/1/long_blade_katana.png",
    black: "/assets/builder/traits/weapon/black/1/long_blade_katana.png",
    label: "Long Blade Katana",
    rarity: 154,
  },
  magical_sceptre: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/magical_sceptre.png",
    tan: "/assets/builder/traits/weapon/tan/1/magical_sceptre.png",
    black: "/assets/builder/traits/weapon/black/1/magical_sceptre.png",
    label: "Magical Sceptre",
    rarity: 151,
  },
  staff: {
    position: 1,
    label: "Staff",
    rarity: 85,
    white: "/assets/builder/traits/weapon/white/1/staff.png",
    black: "/assets/builder/traits/weapon/black/1/staff.png",
    tan: "/assets/builder/traits/weapon/tan/1/staff.png",
  },
  rock: {
    position: 1,
    label: "Rock",
    rarity: 106,
    white: "/assets/builder/traits/weapon/white/1/rock.png",
    black: "/assets/builder/traits/weapon/black/1/rock.png",
    tan: "/assets/builder/traits/weapon/tan/1/rock.png",
  },
  chakra_lightning: {
    position: 1,
    label: "Chakra Lightning",
    rarity: 57,
    white: "/assets/builder/traits/weapon/white/1/chakra_lightning.png",
    black: "/assets/builder/traits/weapon/black/1/chakra_lightning.png",
    tan: "/assets/builder/traits/weapon/tan/1/chakra_lightning.png",
  },
  dark_chakra_lightning: {
    position: 1,
    label: "Dark Chakra Lightning",
    rarity: 19,
    white: "/assets/builder/traits/weapon/white/1/dark_chakra_lightning.png",
    black: "/assets/builder/traits/weapon/black/1/dark_chakra_lightning.png",
    tan: "/assets/builder/traits/weapon/tan/1/dark_chakra_lightning.png",
  },
  galaxy_sword: {
    position: 1,
    label: "Galaxy Sword",
    rarity: 85,
    white: "/assets/builder/traits/weapon/white/1/galaxy_sword.png",
    black: "/assets/builder/traits/weapon/black/1/galaxy_sword.png",
    tan: "/assets/builder/traits/weapon/tan/1/galaxy_sword.png",
  },
  z_sword: {
    position: 1,
    white: "/assets/builder/traits/weapon/white/1/z_sword.png",
    tan: "/assets/builder/traits/weapon/tan/1/z_sword.png",
    black: "/assets/builder/traits/weapon/black/1/z_sword.png",
    label: "Z Sword",
    rarity: 178,
  },
  chakra_energy_ball: {
    position: 2,
    label: "Chakr Energy Ball",
    rarity: 96,
    white: "/assets/builder/traits/weapon/white/2/chakra_energy_ball.png",
    black: "/assets/builder/traits/weapon/black/2/chakra_energy_ball.png",
    tan: "/assets/builder/traits/weapon/tan/2/chakra_energy_ball.png",
  },
  elemental_air: {
    position: 2,
    label: "Elemental Air",
    rarity: 256,
    white: "/assets/builder/traits/weapon/white/2/elemental_air.png",
    black: "/assets/builder/traits/weapon/black/2/elemental_air.png",
    tan: "/assets/builder/traits/weapon/tan/2/elemental_air.png",
  },
  elemental_earth: {
    position: 2,
    label: "Elemental Earth",
    rarity: 151,
    white: "/assets/builder/traits/weapon/white/2/elemental_earth.png",
    black: "/assets/builder/traits/weapon/black/2/elemental_earth.png",
    tan: "/assets/builder/traits/weapon/tan/2/elemental_earth.png",
    zIndex: 4,
  },
  elemental_fire: {
    position: 2,
    label: "Elemental Fire",
    rarity: 271,
    white: "/assets/builder/traits/weapon/white/2/elemental_fire.png",
    black: "/assets/builder/traits/weapon/black/2/elemental_fire.png",
    tan: "/assets/builder/traits/weapon/tan/2/elemental_fire.png",
  },
  elemental_water: {
    position: 2,
    label: "Elemental Water",
    rarity: 157,
    white: "/assets/builder/traits/weapon/white/2/elemental_water.png",
    black: "/assets/builder/traits/weapon/black/2/elemental_water.png",
    tan: "/assets/builder/traits/weapon/tan/2/elemental_water.png",
    zIndex: 4,
  },
  energy_disk: {
    position: 2,
    label: "Energy Disk",
    rarity: 61,
    white: "/assets/builder/traits/weapon/white/2/energy_disk.png",
    black: "/assets/builder/traits/weapon/black/2/energy_disk.png",
    tan: "/assets/builder/traits/weapon/tan/2/energy_disk.png",
  },
  ignition_glove: {
    position: 2,
    label: "Ignition Glove",
    rarity: 116,
    white: "/assets/builder/traits/weapon/white/2/ignition_glove.png",
    black: "/assets/builder/traits/weapon/black/2/ignition_glove.png",
    tan: "/assets/builder/traits/weapon/tan/2/ignition_glove.png",
  },
  rubber_gum: {
    position: 2,
    label: "Rubber Gum ",
    rarity: 200,
    white: "/assets/builder/traits/weapon/white/2/rubber_gum.png",
    black: "/assets/builder/traits/weapon/black/2/rubber_gum.png",
    tan: "/assets/builder/traits/weapon/tan/2/rubber_gum.png",
  },
  volleyball: {
    position: 2,
    label: "Volleyball",
    rarity: 191,
    white: "/assets/builder/traits/weapon/white/2/volleyball.png",
    black: "/assets/builder/traits/weapon/black/2/volleyball.png",
    tan: "/assets/builder/traits/weapon/tan/2/volleyball.png",
  },
  black_devil_sword: {
    position: 3,
    label: "Black Devil Sword",
    rarity: 98,
    white: "/assets/builder/traits/weapon/white/3/black_devil_sword.png",
    black: "/assets/builder/traits/weapon/black/3/black_devil_sword.png",
    tan: "/assets/builder/traits/weapon/tan/3/black_devil_sword.png",
  },
  blue_spirit_sword: {
    position: 3,
    label: "Blue Spirit Sword",
    rarity: 103,
    white: "/assets/builder/traits/weapon/white/3/blue_spirit_sword.png",
    black: "/assets/builder/traits/weapon/black/3/blue_spirit_sword.png",
    tan: "/assets/builder/traits/weapon/tan/3/blue_spirit_sword.png",
  },
  dark_blade: {
    position: 3,
    label: "Dark Blade",
    rarity: 190,
    white: "/assets/builder/traits/weapon/white/3/dark_blade.png",
    black: "/assets/builder/traits/weapon/black/3/dark_blade.png",
    tan: "/assets/builder/traits/weapon/tan/3/dark_blade.png",
  },
  giant_pipe: {
    position: 3,
    label: "Giant Pipe",
    rarity: 182,
    white: "/assets/builder/traits/weapon/white/3/giant_pipe.png",
    black: "/assets/builder/traits/weapon/black/3/giant_pipe.png",
    tan: "/assets/builder/traits/weapon/tan/3/giant_pipe.png",
  },
  legendary_sword: {
    position: 3,
    label: "Legendary Sword",
    rarity: 34,
    white: "/assets/builder/traits/weapon/white/3/legendary_sword.png",
    black: "/assets/builder/traits/weapon/black/3/legendary_sword.png",
    tan: "/assets/builder/traits/weapon/tan/3/legendary_sword.png",
  },
  mist_sword: {
    position: 3,
    label: "Mist Sword",
    rarity: 153,
    white: "/assets/builder/traits/weapon/white/3/mist_sword.png",
    black: "/assets/builder/traits/weapon/black/3/mist_sword.png",
    tan: "/assets/builder/traits/weapon/tan/3/mist_sword.png",
  },
  scissor_blade: {
    position: 3,
    label: "Scissor Blade",
    rarity: 199,
    white: "/assets/builder/traits/weapon/white/3/scissor_blade.png",
    black: "/assets/builder/traits/weapon/black/3/scissor_blade.png",
    tan: "/assets/builder/traits/weapon/tan/3/scissor_blade.png",
  },
  shadow_katana: {
    position: 3,
    label: "Shadow Katana",
    rarity: 251,
    white: "/assets/builder/traits/weapon/white/3/shadow_katana.png",
    black: "/assets/builder/traits/weapon/black/3/shadow_katana.png",
    tan: "/assets/builder/traits/weapon/tan/3/shadow_katana.png",
  },
  soul_reapers_blade: {
    position: 3,
    label: "Soul Reapers Blade",
    rarity: 177,
    white: "/assets/builder/traits/weapon/white/3/soul_reapers_blade.png",
    black: "/assets/builder/traits/weapon/black/3/soul_reapers_blade.png",
    tan: "/assets/builder/traits/weapon/tan/3/soul_reapers_blade.png",
  },
  spirit_blade: {
    position: 3,
    label: "Spirit Blade",
    rarity: 182,
    white: "/assets/builder/traits/weapon/white/3/spirit_blade.png",
    black: "/assets/builder/traits/weapon/black/3/spirit_blade.png",
    tan: "/assets/builder/traits/weapon/tan/3/spirit_blade.png",
  },
  strongest_sword: {
    position: 3,
    label: "Strongest Sword",
    rarity: 181,
    white: "/assets/builder/traits/weapon/white/3/strongest_sword.png",
    black: "/assets/builder/traits/weapon/black/3/strongest_sword.png",
    tan: "/assets/builder/traits/weapon/tan/3/strongest_sword.png",
  },
  spirit_weapon: {
    position: 3,
    label: "Spirit Weapon",
    rarity: 9,
    white: "/assets/builder/traits/weapon/white/3/spirit_weapon.png",
    black: "/assets/builder/traits/weapon/black/3/spirit_weapon.png",
    tan: "/assets/builder/traits/weapon/tan/3/spirit_weapon.png",
  },
};
